# action.yml
name: 'Choco Install'
description: 'install packages on windows using choco'
inputs:
  package-name:  # id of input
    description: 'The package to install'
    required: true
    default: 'lua'
outputs:
  time: # id of output
    description: 'The time it was installed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package-name }}

